# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(870, 530)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.pltWidget = PlotWidget(Form)
        self.pltWidget.setGeometry(QtCore.QRect(210, 20, 641, 221))
        self.pltWidget.setObjectName(_fromUtf8("pltWidget"))
        self.btn_connect = QtGui.QPushButton(Form)
        self.btn_connect.setGeometry(QtCore.QRect(10, 30, 75, 21))
        self.btn_connect.setObjectName(_fromUtf8("btn_connect"))
        self.lbl_connect = QtGui.QLabel(Form)
        self.lbl_connect.setGeometry(QtCore.QRect(120, 30, 81, 20))
        self.lbl_connect.setObjectName(_fromUtf8("lbl_connect"))
        self.lbl_range_min = QtGui.QLabel(Form)
        self.lbl_range_min.setGeometry(QtCore.QRect(20, 62, 91, 20))
        self.lbl_range_min.setObjectName(_fromUtf8("lbl_range_min"))
        self.lbl_range_max = QtGui.QLabel(Form)
        self.lbl_range_max.setGeometry(QtCore.QRect(20, 92, 91, 20))
        self.lbl_range_max.setObjectName(_fromUtf8("lbl_range_max"))
        self.ldt_range_min = QtGui.QLineEdit(Form)
        self.ldt_range_min.setGeometry(QtCore.QRect(120, 60, 51, 21))
        self.ldt_range_min.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_range_min.setObjectName(_fromUtf8("ldt_range_min"))
        self.ldt_range_max = QtGui.QLineEdit(Form)
        self.ldt_range_max.setGeometry(QtCore.QRect(120, 90, 51, 21))
        self.ldt_range_max.setCursorPosition(1)
        self.ldt_range_max.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_range_max.setObjectName(_fromUtf8("ldt_range_max"))
        self.btn_set = QtGui.QPushButton(Form)
        self.btn_set.setGeometry(QtCore.QRect(10, 490, 75, 23))
        self.btn_set.setObjectName(_fromUtf8("btn_set"))
        self.gb_rf_base = QtGui.QGroupBox(Form)
        self.gb_rf_base.setGeometry(QtCore.QRect(10, 420, 161, 61))
        self.gb_rf_base.setObjectName(_fromUtf8("gb_rf_base"))
        self.rb_rf = QtGui.QRadioButton(self.gb_rf_base)
        self.rb_rf.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.rb_rf.setObjectName(_fromUtf8("rb_rf"))
        self.rb_base = QtGui.QRadioButton(self.gb_rf_base)
        self.rb_base.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.rb_base.setChecked(True)
        self.rb_base.setObjectName(_fromUtf8("rb_base"))
        self.btn_pause = QtGui.QPushButton(Form)
        self.btn_pause.setGeometry(QtCore.QRect(100, 490, 75, 23))
        self.btn_pause.setObjectName(_fromUtf8("btn_pause"))
        self.btn_resume = QtGui.QPushButton(Form)
        self.btn_resume.setGeometry(QtCore.QRect(210, 490, 75, 23))
        self.btn_resume.setObjectName(_fromUtf8("btn_resume"))
        self.lbl_FPS = QtGui.QLabel(Form)
        self.lbl_FPS.setGeometry(QtCore.QRect(20, 270, 91, 20))
        self.lbl_FPS.setObjectName(_fromUtf8("lbl_FPS"))
        self.ldt_FPS = QtGui.QLineEdit(Form)
        self.ldt_FPS.setGeometry(QtCore.QRect(120, 270, 51, 21))
        self.ldt_FPS.setCursorPosition(1)
        self.ldt_FPS.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_FPS.setObjectName(_fromUtf8("ldt_FPS"))
        self.lbl_tx_power = QtGui.QLabel(Form)
        self.lbl_tx_power.setGeometry(QtCore.QRect(20, 300, 91, 20))
        self.lbl_tx_power.setObjectName(_fromUtf8("lbl_tx_power"))
        self.ldt_tx_power = QtGui.QLineEdit(Form)
        self.ldt_tx_power.setGeometry(QtCore.QRect(120, 300, 51, 21))
        self.ldt_tx_power.setCursorPosition(1)
        self.ldt_tx_power.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_tx_power.setObjectName(_fromUtf8("ldt_tx_power"))
        self.lbl_dac_min = QtGui.QLabel(Form)
        self.lbl_dac_min.setGeometry(QtCore.QRect(20, 120, 91, 20))
        self.lbl_dac_min.setObjectName(_fromUtf8("lbl_dac_min"))
        self.lbl_dac_max = QtGui.QLabel(Form)
        self.lbl_dac_max.setGeometry(QtCore.QRect(20, 150, 91, 20))
        self.lbl_dac_max.setObjectName(_fromUtf8("lbl_dac_max"))
        self.ldt_dac_min = QtGui.QLineEdit(Form)
        self.ldt_dac_min.setGeometry(QtCore.QRect(120, 120, 51, 21))
        self.ldt_dac_min.setCursorPosition(3)
        self.ldt_dac_min.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_dac_min.setObjectName(_fromUtf8("ldt_dac_min"))
        self.ldt_dac_max = QtGui.QLineEdit(Form)
        self.ldt_dac_max.setGeometry(QtCore.QRect(120, 150, 51, 21))
        self.ldt_dac_max.setCursorPosition(4)
        self.ldt_dac_max.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_dac_max.setObjectName(_fromUtf8("ldt_dac_max"))
        self.lbl_iterations = QtGui.QLabel(Form)
        self.lbl_iterations.setGeometry(QtCore.QRect(20, 180, 91, 20))
        self.lbl_iterations.setObjectName(_fromUtf8("lbl_iterations"))
        self.ldt_iterations = QtGui.QLineEdit(Form)
        self.ldt_iterations.setGeometry(QtCore.QRect(120, 180, 51, 21))
        self.ldt_iterations.setCursorPosition(3)
        self.ldt_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_iterations.setObjectName(_fromUtf8("ldt_iterations"))
        self.lbl_pulse_per_step = QtGui.QLabel(Form)
        self.lbl_pulse_per_step.setGeometry(QtCore.QRect(20, 210, 91, 20))
        self.lbl_pulse_per_step.setObjectName(_fromUtf8("lbl_pulse_per_step"))
        self.ldt_pulse_per_step = QtGui.QLineEdit(Form)
        self.ldt_pulse_per_step.setGeometry(QtCore.QRect(120, 210, 51, 21))
        self.ldt_pulse_per_step.setCursorPosition(3)
        self.ldt_pulse_per_step.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_pulse_per_step.setObjectName(_fromUtf8("ldt_pulse_per_step"))
        self.ldt_PRF = QtGui.QLineEdit(Form)
        self.ldt_PRF.setGeometry(QtCore.QRect(120, 240, 51, 21))
        self.ldt_PRF.setCursorPosition(2)
        self.ldt_PRF.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_PRF.setObjectName(_fromUtf8("ldt_PRF"))
        self.lbl_PRF = QtGui.QLabel(Form)
        self.lbl_PRF.setGeometry(QtCore.QRect(20, 240, 91, 20))
        self.lbl_PRF.setObjectName(_fromUtf8("lbl_PRF"))
        self.lbl_iso_level = QtGui.QLabel(Form)
        self.lbl_iso_level.setGeometry(QtCore.QRect(20, 330, 91, 20))
        self.lbl_iso_level.setObjectName(_fromUtf8("lbl_iso_level"))
        self.ldt_iso_level = QtGui.QLineEdit(Form)
        self.ldt_iso_level.setGeometry(QtCore.QRect(120, 330, 51, 21))
        self.ldt_iso_level.setCursorPosition(4)
        self.ldt_iso_level.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_iso_level.setObjectName(_fromUtf8("ldt_iso_level"))
        self.lbl_scan_range = QtGui.QLabel(Form)
        self.lbl_scan_range.setGeometry(QtCore.QRect(20, 360, 91, 20))
        self.lbl_scan_range.setObjectName(_fromUtf8("lbl_scan_range"))
        self.ldt_scan_range = QtGui.QLineEdit(Form)
        self.ldt_scan_range.setGeometry(QtCore.QRect(120, 360, 51, 21))
        self.ldt_scan_range.setCursorPosition(1)
        self.ldt_scan_range.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_scan_range.setObjectName(_fromUtf8("ldt_scan_range"))
        self.lbl_resolution = QtGui.QLabel(Form)
        self.lbl_resolution.setGeometry(QtCore.QRect(20, 390, 91, 20))
        self.lbl_resolution.setObjectName(_fromUtf8("lbl_resolution"))
        self.ldt_resolution = QtGui.QLineEdit(Form)
        self.ldt_resolution.setGeometry(QtCore.QRect(120, 390, 51, 21))
        self.ldt_resolution.setCursorPosition(3)
        self.ldt_resolution.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_resolution.setObjectName(_fromUtf8("ldt_resolution"))
        self.lbl_distance = QtGui.QLabel(Form)
        self.lbl_distance.setGeometry(QtCore.QRect(480, 490, 81, 20))
        self.lbl_distance.setObjectName(_fromUtf8("lbl_distance"))
        self.ldt_distance = QtGui.QLineEdit(Form)
        self.ldt_distance.setGeometry(QtCore.QRect(570, 490, 81, 21))
        self.ldt_distance.setCursorPosition(1)
        self.ldt_distance.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_distance.setObjectName(_fromUtf8("ldt_distance"))
        self.pltWidget_2 = PlotWidget(Form)
        self.pltWidget_2.setGeometry(QtCore.QRect(210, 250, 641, 231))
        self.pltWidget_2.setObjectName(_fromUtf8("pltWidget_2"))
        self.btn_Background = QtGui.QPushButton(Form)
        self.btn_Background.setGeometry(QtCore.QRect(390, 490, 75, 23))
        self.btn_Background.setObjectName(_fromUtf8("btn_Background"))
        self.lbl_distance_2 = QtGui.QLabel(Form)
        self.lbl_distance_2.setGeometry(QtCore.QRect(670, 490, 81, 20))
        self.lbl_distance_2.setObjectName(_fromUtf8("lbl_distance_2"))
        self.ldt_distance_2 = QtGui.QLineEdit(Form)
        self.ldt_distance_2.setGeometry(QtCore.QRect(770, 490, 81, 21))
        self.ldt_distance_2.setCursorPosition(1)
        self.ldt_distance_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ldt_distance_2.setObjectName(_fromUtf8("ldt_distance_2"))
        self.btn_save = QtGui.QPushButton(Form)
        self.btn_save.setGeometry(QtCore.QRect(300, 490, 75, 23))
        self.btn_save.setObjectName(_fromUtf8("btn_save"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.btn_connect.setText(_translate("Form", "Connect", None))
        self.lbl_connect.setText(_translate("Form", "TextLabel", None))
        self.lbl_range_min.setText(_translate("Form", "Range Min", None))
        self.lbl_range_max.setText(_translate("Form", "Range Max", None))
        self.ldt_range_min.setText(_translate("Form", "0.8", None))
        self.ldt_range_max.setText(_translate("Form", "1.6", None))
        self.btn_set.setText(_translate("Form", "Set", None))
        self.gb_rf_base.setTitle(_translate("Form", "Baseband/RF", None))
        self.rb_rf.setText(_translate("Form", "RF", None))
        self.rb_base.setText(_translate("Form", "Baseband", None))
        self.btn_pause.setText(_translate("Form", "Pause", None))
        self.btn_resume.setText(_translate("Form", "Resume", None))
        self.lbl_FPS.setText(_translate("Form", "FPS", None))
        self.ldt_FPS.setText(_translate("Form", "5", None))
        self.lbl_tx_power.setText(_translate("Form", "Tx Power", None))
        self.ldt_tx_power.setText(_translate("Form", "2", None))
        self.lbl_dac_min.setText(_translate("Form", "DAC Min", None))
        self.lbl_dac_max.setText(_translate("Form", "DAC Max", None))
        self.ldt_dac_min.setText(_translate("Form", "900", None))
        self.ldt_dac_max.setText(_translate("Form", "1150", None))
        self.lbl_iterations.setText(_translate("Form", "Iterations", None))
        self.ldt_iterations.setText(_translate("Form", "128", None))
        self.lbl_pulse_per_step.setText(_translate("Form", "PPS", None))
        self.ldt_pulse_per_step.setText(_translate("Form", "128", None))
        self.ldt_PRF.setText(_translate("Form", "30", None))
        self.lbl_PRF.setText(_translate("Form", "PRF", None))
        self.lbl_iso_level.setText(_translate("Form", "ISO Level", None))
        self.ldt_iso_level.setText(_translate("Form", "0.01", None))
        self.lbl_scan_range.setText(_translate("Form", "Scan Range", None))
        self.ldt_scan_range.setText(_translate("Form", "0", None))
        self.lbl_resolution.setText(_translate("Form", "Resolution", None))
        self.ldt_resolution.setText(_translate("Form", "0.8", None))
        self.lbl_distance.setText(_translate("Form", "DistanceO", None))
        self.ldt_distance.setText(_translate("Form", "0", None))
        self.btn_Background.setText(_translate("Form", "Backg", None))
        self.lbl_distance_2.setText(_translate("Form", "DistanceS", None))
        self.ldt_distance_2.setText(_translate("Form", "0", None))
        self.btn_save.setText(_translate("Form", "Save", None))

from pyqtgraph import PlotWidget
